# my global config
global:
  scrape_interval: 1s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1s 

rule_files:
  - "/etc/prometheus/rules/bms.rules"
  - "/etc/prometheus/rules/swarm.rules"
  - "/etc/prometheus/rules/resource.rules"

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker-cadvisor'
    dns_sd_configs:   # Use Docker Swarm's built-in DNS server to discover services
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080
  
  - job_name: 'docker-swarm'
    dns_sd_configs:
    - names:
      - 'tasks.swarm-exporter'
      type: 'A'
      port: 5051
  - job_name: 'business_microservices'
    dns_sd_configs:
    - names:
      - 'tasks.business_web_1'
      - 'tasks.business_web_2'
      - 'tasks.business_web_3'
      type: 'A'
      port: 80